### ISSUE TITLE
Get job report artifacts clarification

### ISSUE THREAD

**Issue by ilyaglow** [CERT-BDF/CortexDocs#5]
Hello,

Thank you for this repo, it helped me a ton to write a Cortex [client library in Go](https://github.com/ilyaglow/go-cortex)! And of course thanks for Cortex itself too :)

While I was writing tests I noticed that an example output in the [documentation for getting job report](https://github.com/CERT-BDF/CortexDocs/blob/master/api/get-job-report.md) and the real Cortex output are different.

The hyperlink above declares an `Artifact` inside a `Report` object as a flat object with two attributes: 
```
{
 "type": "sha1",
 "value": "cd1c2da4de388a4b5b60601f8b339518fe8fbd31"
}
```

But in fact the scheme of an `Artifact` is the same as an `Observable Artifact`:
```
{
  "attributes": {
    "dataType": "ip"
  },
  "data": "8.8.4.4"
}
```

Which seems kinda wrong to me so maybe it's actually a Cortex bug.
What you think?

**Comment by 3c7** [comment]
Sorry, but where does
```json
{
  "attributes": {
    "dataType": "ip"
  },
  "data": "8.8.4.4"
}
```
come from?
The request for querying an analyzer is:
```json
{
  "dataType": "ip",
  "data": "1.2.3.4"
}
```
So I'm struggling to understand the issue. ;)

**Comment by ilyaglow** [comment]
It comes from a job response not a request :)

Ok, I'll try to be more specific. This is an excerpt from the job response [example](https://github.com/CERT-BDF/CortexDocs/blob/master/api/get-job-report.md) with an _artifacts array_ (quote: "An array of the artifacts extracted from the analysis") and what seems Cortex is intended to return or was returning, but actually _does not_ return:
```json
 "report": {
    "artifacts": [
      {
        "type": "sha1",
        "value": "cd1c2da4de388a4b5b60601f8b339518fe8fbd31"
      },
      {
        "type": "sha256",
        "value": "fd1755c7f1f0f85597cf2a1f13f5cbe0782d9e5597aca410da0d5f26cda26b97"
      },
      {
        "type": "md5",
        "value": "3aa598d1f0d50228d48fe3a792071dde"
      }
    ],
  "full": {
   ...
  }
}
```

This is how Cortex _actually_ responds with an artifacts array:
```json
 "report": {
    "artifacts": [
      {
       "attributes": {
           "dataType": "sha1"
        },
        "data": "cd1c2da4de388a4b5b60601f8b339518fe8fbd31"
      },
      {
       "attributes": {
           "dataType": "sha256"
        },
        "data": "fd1755c7f1f0f85597cf2a1f13f5cbe0782d9e5597aca410da0d5f26cda26b97"
      },
      {
        "attributes": {
           "dataType": "md5"
        },
        "data": "3aa598d1f0d50228d48fe3a792071dde"
      }
    ],
  "full": {
   ...
  }
}
```

So my points are:
1. The documentation is clearly wrong as is.
2. But it seems that documentation provides a better model for an artifacts array rather than it actually is, so maybe it would be better to fix Cortex instead of docs ;)

**Comment by nadouani** [comment]
Hello guys,

well, I can understand this is strange, but Cortex parses/transforms the `artifacts` coming from the analyzers output to make to comply to it's internal artifact/observable structure.

The docs show the right Job structure when returned by Cortex.

Note that until now, we don't consume the data related to the extracted artifacts, so we didn't get deep on that area.

**Comment by nadouani** [comment]
That said, the following page is wrong

https://github.com/CERT-BDF/CortexDocs/blob/master/api/get-job-report.md

:)

**Comment by 3c7** [comment]
@ilyaglow Well, sorry - it's monday. ;)

**Comment by ilyaglow** [comment]
That's fine, I'm glad that the issue is resolved now, either way :) Hope it will help someone to not shoot in the foot, like I did.
